# Generated by Django 4.1.3 on 2022-12-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="updated_date",
        ),
    ]
